# Generated by Django 3.1.7 on 2021-04-30 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('date_naissance', models.DateTimeField(default=datetime.date.today)),
                ('date_embauche', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foncion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rtt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rtt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=datetime.date.today)),
                ('date_fin', models.DateTimeField(default=datetime.date.today)),
                ('chargepatronales', models.FloatField()),
                ('charge_salariales', models.FloatField()),
                ('sal_brut', models.FloatField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.foncion'),
        ),
        migrations.AddField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.service'),
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=datetime.date.today)),
                ('date_fin', models.DateTimeField(default=datetime.date.today)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.employe')),
            ],
        ),
    ]
